from flask import Flask, jsonify, request
from flask_cors import CORS
from datetime import datetime
import random
import uuid

app = Flask(__name__)
CORS(app)

class AIWebService:
    """
    Backend service that provides APIs for:
    - Chatbot
    - Content Generator
    - Recommendation Engine
    """

    def __init__(self):
        self.chat_history = []
        self.recommendations = self._seed_recommendations()

    def _seed_recommendations(self):
        return [
            {
                "id": str(uuid.uuid4()),
                "title": "Learn Python",
                "description": "Improve your backend development skills.",
                "category": "education",
                "score": 95
            },
            {
                "id": str(uuid.uuid4()),
                "title": "Build REST APIs",
                "description": "Practice creating scalable APIs using Flask.",
                "category": "technology",
                "score": 92
            },
            {
                "id": str(uuid.uuid4()),
                "title": "Read AI Articles",
                "description": "Stay updated with the latest AI trends.",
                "category": "technology",
                "score": 90
            },
            {
                "id": str(uuid.uuid4()),
                "title": "Financial Planning",
                "description": "Track your monthly expenses effectively.",
                "category": "finance",
                "score": 84
            }
        ]

    def generate_chat_response(self, message):
        responses = [
            "That's an interesting question.",
            "I understand your request.",
            "Let me help you with that.",
            "Here is a possible solution.",
            "Thanks for asking!"
        ]

        response = random.choice(responses)

        conversation = {
            "timestamp": datetime.utcnow().isoformat(),
            "user": message,
            "assistant": response
        }

        self.chat_history.append(conversation)

        return conversation

    def generate_content(self, payload):
        topic = payload.get("topic", "Untitled")
        content_type = payload.get("type", "article")
        tone = payload.get("tone", "professional")
        length = payload.get("length", "medium")

        content = (
            f"{content_type.title()} about {topic}\n\n"
            f"Tone: {tone}\n"
            f"Length: {length}\n\n"
            f"This content was generated by the AI Web Service."
        )

        return {
            "content": content
        }

    def get_recommendations(self):
        return self.recommendations


service = AIWebService()
@app.route("/")
def home():
    return jsonify({
        "service": "AI Web Service",
        "status": "running",
        "version": "1.0.0"
    })


@app.route("/api/health", methods=["GET"])
def health():
    return jsonify({
        "status": "healthy",
        "timestamp": datetime.utcnow().isoformat()
    })


@app.route("/api/ai/chat", methods=["POST"])
def chat():

    data = request.get_json(silent=True) or {}

    message = data.get("message")

    if not message:
        return jsonify({
            "error": "Message is required."
        }), 400

    response = service.generate_chat_response(message)

    return jsonify(response)


@app.route("/api/ai/generate", methods=["POST"])
def generate():

    payload = request.get_json(silent=True) or {}

    if not payload.get("topic"):
        return jsonify({
            "error": "Topic is required."
        }), 400

    result = service.generate_content(payload)

    return jsonify(result)


@app.route("/api/ai/recommendations", methods=["GET"])
def recommendations():

    return jsonify({
        "recommendations": service.get_recommendations()
    })
@app.route("/api/history", methods=["GET"])
def history():

    return jsonify({
        "history": service.chat_history
    })


@app.route("/api/history", methods=["DELETE"])
def clear_history():

    service.chat_history.clear()

    return jsonify({
        "message": "Chat history cleared successfully."
    })


@app.errorhandler(404)
def not_found(error):

    return jsonify({
        "error": "Endpoint not found."
    }), 404


@app.errorhandler(500)
def internal_error(error):

    return jsonify({
        "error": "Internal server error."
    }), 500


if __name__ == "__main__":
    app.run(
        host="0.0.0.0",
        port=5000,
        debug=True,
        use_reloader=False
    )