# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sda-training-secrets
  namespace: sda-training
type: Opaque
data:
  JWT_SECRET: c3VwZXJzZWNyZXQNCg==
  MONGODB_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9zZGFfdHJhaW5pbmcNCg==
  POSTGRES_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzcWwtc2VydmljZTo1NDMyL3NkYV90cmFpbmluZw0K
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkNCg==
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQNCg==
  POSTGRES_PASSWORD: cGFzc3dvcmQNCg==