apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-logs-pv
  labels:
    app: sda-training
    component: logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/sda-training/logs
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-uploads-pv
  labels:
    app: sda-training
    component: uploads
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/sda-training/uploads
    type: DirectoryOrCreate