apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sda-training
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "sda-training-app"
        static_configs:
          - targets:
              - "sda-training-service:3000"

      - job_name: "prometheus"
        static_configs:
          - targets:
              - "localhost:9090"