apiVersion: v1
kind: Secret

metadata:
  name: sda-training-secrets
  namespace: sda-training

type: Opaque

data:
  JWT_SECRET: <base64-encoded-secret>
  MONGODB_URI: <base64-encoded-mongodb-uri>
  POSTGRES_URL: <base64-encoded-postgres-url>
  REDIS_URL: <base64-encoded-redis-url>