from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
import uvicorn

app = FastAPI(
    title="Mobile AI Service",
    version="1.0.0",
    description="AI backend for the Day 26 Mobile Application"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
class ChatRequest(BaseModel):
    message: str
    conversation_history: Optional[List[str]] = []


class ChatResponse(BaseModel):
    response: str


class ContentGenerationRequest(BaseModel):
    topic: str
    content_type: str
    max_length: Optional[int] = 200


class ContentGenerationResponse(BaseModel):
    content: str


class RecommendationRequest(BaseModel):
    preferences: List[str]


class RecommendationResponse(BaseModel):
    recommendations: List[str]


class FeedbackRequest(BaseModel):
    message: str
    rating: int
@app.get("/health")
async def health_check():
    return {
        "status": "healthy",
        "service": "Mobile AI Service",
        "version": "1.0.0",
        "message": "API is running successfully"
    }
@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    try:
        user_message = request.message.strip()

        if not user_message:
            raise HTTPException(
                status_code=400,
                detail="Message cannot be empty."
            )

        response = (
            f"You said: '{user_message}'. "
            f"This is a sample AI response from the Mobile AI Service."
        )

        return ChatResponse(
            response=response
        )

    except HTTPException:
        raise

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Chat service error: {str(e)}"
        )
@app.post("/generate-content", response_model=ContentGenerationResponse)
async def generate_content(request: ContentGenerationRequest):
    try:
        topic = request.topic.strip()
        content_type = request.content_type.strip()

        if not topic:
            raise HTTPException(
                status_code=400,
                detail="Topic cannot be empty."
            )

        generated_content = f"""
{content_type.title()}: {topic}

Introduction
------------
This is an AI-generated {content_type.lower()} about "{topic}".

Key Points
----------
• Understand the fundamentals of {topic}.
• Learn practical applications.
• Follow best practices.
• Continue improving through regular practice.

Conclusion
----------
This content was generated by the Mobile AI Service backend and can be replaced with a real AI model such as OpenAI, Gemini, or any LLM.
""".strip()

        return ContentGenerationResponse(
            content=generated_content
        )

    except HTTPException:
        raise

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Content generation failed: {str(e)}"
        )
@app.post("/recommendations", response_model=RecommendationResponse)
async def get_recommendations(request: RecommendationRequest):
    try:
        if not request.preferences:
            raise HTTPException(
                status_code=400,
                detail="At least one preference is required."
            )

        recommendations = []

        for preference in request.preferences:
            preference = preference.strip()

            if preference:
                recommendations.extend([
                    f"Learn more about {preference}",
                    f"Explore advanced {preference} tutorials",
                    f"Build a project using {preference}",
                ])

        recommendations = list(dict.fromkeys(recommendations))

        return RecommendationResponse(
            recommendations=recommendations
        )

    except HTTPException:
        raise

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Recommendation service failed: {str(e)}"
        )
@app.post("/feedback")
async def submit_feedback(request: FeedbackRequest):
    try:
        if request.rating < 1 or request.rating > 5:
            raise HTTPException(
                status_code=400,
                detail="Rating must be between 1 and 5."
            )

        return {
            "status": "success",
            "message": "Feedback submitted successfully.",
            "feedback": {
                "message": request.message,
                "rating": request.rating,
            },
        }

    except HTTPException:
        raise

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Feedback service failed: {str(e)}"
        )

if __name__ == "__main__":
    uvicorn.run(
        "mobile_ai_service:app",
        host="0.0.0.0",
        port=5000,
        reload=True,
    )